name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # use action actions/checkout@v4 to checkout the repository
        uses: actions/checkout@v4
        with :
          repository: ''

      # use action actions/setup-java@v4 and version 21 and the distribution corretto
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -B package --file pom.xml